### ISSUE TITLE
Viper requires old version of asn1crypto, which breaks pip on macOS Catalina

### ISSUE THREAD

**Issue by toomanybananas** [viper-framework/viper#784]
viper-modules requires asn1crypto==0.24.0, however that version of asn1crypto is broken on the newest version of macOS and will cause viper (as well as many other python packages) to segfault on startup (see https://github.com/Homebrew/homebrew-core/issues/44996).

Upgrading to the latest version seems to work fine for me.

**Comment by botherder** [comment]
Should be fixed now. Could you please try with `update-modules`?

**Comment by toomanybananas** [comment]
Not fixed, see https://github.com/viper-framework/viper-modules/blob/master/requirements.txt#L47.

Still wants asn1crypto==0.2.4
